-- Instalação completa: conectar ao banco gestao_laboratorio e executar.
-- Não inclui dados fictícios. Conteúdo: 01_schema.sql + 02_regras.sql.

-- Sistema de Gestão de Laboratório de Pesquisa — PostgreSQL 16 ou superior.
-- Executar uma única vez em banco vazio. Não apaga nem substitui dados existentes.
-- As regras e funções complementares estão em 02_regras.sql.
BEGIN;
CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;
CREATE SCHEMA gestao_lab;
SET LOCAL search_path = gestao_lab, public;
SET LOCAL TIME ZONE 'America/Sao_Paulo';

CREATE TYPE tipo_recurso AS ENUM ('SALA', 'BANCADA', 'EQUIPAMENTO');
CREATE TYPE estado_recurso AS ENUM ('DISPONIVEL', 'MANUTENCAO', 'DANIFICADO', 'DESATIVADO');
CREATE TYPE tipo_aluno AS ENUM ('GRADUACAO', 'MESTRADO', 'DOUTORADO', 'POS');
CREATE TYPE estado_reserva AS ENUM ('CONFIRMADA', 'CANCELADA', 'CONCLUIDA');
-- EM_USO é derivado de empréstimo aberto, nunca um estado manual da cópia.
CREATE TYPE condicao_chave AS ENUM ('OPERACIONAL', 'EXTRAVIADA', 'INDISPONIVEL');
CREATE TYPE estado_solicitacao AS ENUM ('PENDENTE', 'APROVADA', 'NEGADA');
CREATE TYPE estado_protocolo AS ENUM ('NAO_VALIDADO', 'VALIDADO');
CREATE TYPE estado_envio AS ENUM ('PENDENTE', 'ENVIADO', 'FALHOU');

CREATE TABLE laboratorio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL CHECK (btrim(nome) <> ''),
    localizacao text NOT NULL CHECK (btrim(localizacao) <> ''),
    chefe_usuario_id bigint NOT NULL,
    -- NULL significa limite ainda não configurado; não se inventa valor padrão.
    duracao_maxima_reserva interval CHECK (duracao_maxima_reserva > interval '0' AND isfinite(duracao_maxima_reserva)),
    max_reservas_simultaneas integer CHECK (max_reservas_simultaneas > 0),
    dias_alerta_validade integer NOT NULL DEFAULT 30 CHECK (dias_alerta_validade >= 0),
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id) DEFERRABLE INITIALLY DEFERRED,
    nome text NOT NULL CHECK (btrim(nome) <> ''),
    email text NOT NULL UNIQUE CHECK (email = lower(btrim(email)) AND email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
    senha_hash text NOT NULL CHECK (length(senha_hash) >= 40),
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (id, laboratorio_id)
);
CREATE TABLE professor (
    usuario_id bigint PRIMARY KEY,
    laboratorio_id bigint NOT NULL,
    programa_pos text NOT NULL CHECK (btrim(programa_pos) <> ''),
    ramal text,
    UNIQUE (usuario_id, laboratorio_id),
    FOREIGN KEY (usuario_id, laboratorio_id) REFERENCES usuario(id, laboratorio_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE aluno (
    usuario_id bigint PRIMARY KEY,
    laboratorio_id bigint NOT NULL,
    matricula text NOT NULL UNIQUE CHECK (btrim(matricula) <> ''),
    tipo tipo_aluno NOT NULL,
    orientador_usuario_id bigint NOT NULL,
    UNIQUE (usuario_id, laboratorio_id),
    FOREIGN KEY (usuario_id, laboratorio_id) REFERENCES usuario(id, laboratorio_id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (orientador_usuario_id, laboratorio_id) REFERENCES professor(usuario_id, laboratorio_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE chefe_laboratorio (
    usuario_id bigint PRIMARY KEY,
    laboratorio_id bigint NOT NULL UNIQUE,
    UNIQUE (usuario_id, laboratorio_id),
    FOREIGN KEY (usuario_id, laboratorio_id) REFERENCES professor(usuario_id, laboratorio_id) DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE laboratorio ADD CONSTRAINT laboratorio_chefe_fk
    FOREIGN KEY (chefe_usuario_id, id) REFERENCES chefe_laboratorio(usuario_id, laboratorio_id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE sessao_usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL REFERENCES usuario(id),
    token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    expira_em timestamptz NOT NULL,
    revogado_em timestamptz,
    CHECK (expira_em > criado_em),
    CHECK (revogado_em IS NULL OR revogado_em >= criado_em)
);

CREATE TABLE recurso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    tipo tipo_recurso NOT NULL,
    nome text NOT NULL CHECK (btrim(nome) <> ''),
    estado estado_recurso NOT NULL DEFAULT 'DISPONIVEL',
    responsavel_usuario_id bigint NOT NULL,
    observacao text,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (id, laboratorio_id),
    UNIQUE (id, tipo),
    FOREIGN KEY (responsavel_usuario_id, laboratorio_id) REFERENCES professor(usuario_id, laboratorio_id)
);
CREATE TABLE sala (
    recurso_id bigint PRIMARY KEY,
    laboratorio_id bigint NOT NULL,
    tipo tipo_recurso GENERATED ALWAYS AS ('SALA'::tipo_recurso) STORED,
    identificacao text NOT NULL CHECK (btrim(identificacao) <> ''),
    localizacao text NOT NULL CHECK (btrim(localizacao) <> ''),
    capacidade integer NOT NULL CHECK (capacidade > 0),
    UNIQUE (recurso_id, laboratorio_id),
    UNIQUE (laboratorio_id, identificacao),
    FOREIGN KEY (recurso_id, laboratorio_id) REFERENCES recurso(id, laboratorio_id),
    FOREIGN KEY (recurso_id, tipo) REFERENCES recurso(id, tipo)
);
CREATE TABLE bancada (
    recurso_id bigint PRIMARY KEY,
    laboratorio_id bigint NOT NULL,
    tipo tipo_recurso GENERATED ALWAYS AS ('BANCADA'::tipo_recurso) STORED,
    sala_id bigint NOT NULL,
    numero_identificacao text NOT NULL CHECK (btrim(numero_identificacao) <> ''),
    UNIQUE (recurso_id, laboratorio_id),
    UNIQUE (sala_id, numero_identificacao),
    FOREIGN KEY (recurso_id, laboratorio_id) REFERENCES recurso(id, laboratorio_id),
    FOREIGN KEY (recurso_id, tipo) REFERENCES recurso(id, tipo),
    FOREIGN KEY (sala_id, laboratorio_id) REFERENCES sala(recurso_id, laboratorio_id)
);
CREATE TABLE equipamento (
    recurso_id bigint PRIMARY KEY,
    laboratorio_id bigint NOT NULL,
    tipo tipo_recurso GENERATED ALWAYS AS ('EQUIPAMENTO'::tipo_recurso) STORED,
    numero_patrimonio text NOT NULL UNIQUE CHECK (btrim(numero_patrimonio) <> ''),
    bancada_id bigint,
    sala_direta_id bigint,
    complemento_local text NOT NULL CHECK (btrim(complemento_local) <> ''),
    foto_uri text,
    UNIQUE (recurso_id, laboratorio_id),
    CHECK (num_nonnulls(bancada_id, sala_direta_id) = 1),
    FOREIGN KEY (recurso_id, laboratorio_id) REFERENCES recurso(id, laboratorio_id),
    FOREIGN KEY (recurso_id, tipo) REFERENCES recurso(id, tipo),
    FOREIGN KEY (bancada_id, laboratorio_id) REFERENCES bancada(recurso_id, laboratorio_id),
    FOREIGN KEY (sala_direta_id, laboratorio_id) REFERENCES sala(recurso_id, laboratorio_id)
);

CREATE TABLE reserva (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    usuario_id bigint NOT NULL,
    recurso_principal_id bigint NOT NULL,
    inicio timestamptz NOT NULL,
    fim timestamptz NOT NULL,
    periodo tstzrange GENERATED ALWAYS AS (tstzrange(inicio, fim, '[)')) STORED,
    estado estado_reserva NOT NULL DEFAULT 'CONFIRMADA',
    bloqueia boolean GENERATED ALWAYS AS (estado = 'CONFIRMADA') STORED,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    cancelado_em timestamptz,
    cancelado_por bigint,
    motivo_cancelamento text,
    UNIQUE (id, laboratorio_id),
    UNIQUE (id, periodo, bloqueia),
    CHECK (isfinite(inicio) AND isfinite(fim) AND fim > inicio),
    CHECK ((estado = 'CANCELADA' AND cancelado_em IS NOT NULL AND cancelado_por IS NOT NULL AND nullif(btrim(motivo_cancelamento), '') IS NOT NULL)
        OR (estado <> 'CANCELADA' AND cancelado_em IS NULL AND cancelado_por IS NULL AND motivo_cancelamento IS NULL)),
    FOREIGN KEY (usuario_id, laboratorio_id) REFERENCES usuario(id, laboratorio_id),
    FOREIGN KEY (recurso_principal_id, laboratorio_id) REFERENCES recurso(id, laboratorio_id),
    FOREIGN KEY (cancelado_por, laboratorio_id) REFERENCES usuario(id, laboratorio_id)
);
CREATE TABLE reserva_recurso (
    reserva_id bigint NOT NULL,
    recurso_id bigint NOT NULL,
    laboratorio_id bigint NOT NULL,
    periodo tstzrange NOT NULL,
    bloqueia boolean NOT NULL,
    -- Fotografia textual do local na confirmação; permanece após futuras mudanças.
    local_registrado jsonb NOT NULL,
    PRIMARY KEY (reserva_id, recurso_id),
    FOREIGN KEY (reserva_id, laboratorio_id) REFERENCES reserva(id, laboratorio_id),
    FOREIGN KEY (recurso_id, laboratorio_id) REFERENCES recurso(id, laboratorio_id),
    FOREIGN KEY (reserva_id, periodo, bloqueia) REFERENCES reserva(id, periodo, bloqueia) ON UPDATE CASCADE,
    CONSTRAINT reserva_recurso_sem_sobreposicao EXCLUDE USING gist
        (recurso_id WITH =, periodo WITH &&) WHERE (bloqueia)
);

CREATE TABLE chave (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    codigo_copia text NOT NULL UNIQUE CHECK (btrim(codigo_copia) <> ''),
    sala_id bigint,
    bancada_id bigint,
    condicao condicao_chave NOT NULL DEFAULT 'OPERACIONAL',
    designada_por bigint NOT NULL,
    -- NULL: cópia compartilhada. Preenchido: cópia designada a este usuário.
    designada_para bigint,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (id, laboratorio_id),
    CHECK (num_nonnulls(sala_id, bancada_id) = 1),
    FOREIGN KEY (sala_id, laboratorio_id) REFERENCES sala(recurso_id, laboratorio_id),
    FOREIGN KEY (bancada_id, laboratorio_id) REFERENCES bancada(recurso_id, laboratorio_id),
    FOREIGN KEY (designada_por, laboratorio_id) REFERENCES professor(usuario_id, laboratorio_id),
    FOREIGN KEY (designada_para, laboratorio_id) REFERENCES usuario(id, laboratorio_id)
);
CREATE TABLE emprestimo_chave (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    chave_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    reserva_id bigint NOT NULL,
    retirada_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    entregue_por bigint NOT NULL,
    devolucao_em timestamptz,
    recebido_por bigint,
    UNIQUE (id, laboratorio_id),
    CHECK ((devolucao_em IS NULL) = (recebido_por IS NULL)),
    CHECK (devolucao_em IS NULL OR devolucao_em >= retirada_em),
    FOREIGN KEY (chave_id, laboratorio_id) REFERENCES chave(id, laboratorio_id),
    FOREIGN KEY (usuario_id, laboratorio_id) REFERENCES usuario(id, laboratorio_id),
    FOREIGN KEY (reserva_id, laboratorio_id) REFERENCES reserva(id, laboratorio_id),
    FOREIGN KEY (entregue_por, laboratorio_id) REFERENCES professor(usuario_id, laboratorio_id),
    FOREIGN KEY (recebido_por, laboratorio_id) REFERENCES professor(usuario_id, laboratorio_id)
);
CREATE UNIQUE INDEX emprestimo_chave_uma_posse_aberta ON emprestimo_chave(chave_id) WHERE devolucao_em IS NULL;
CREATE TABLE ocorrencia_chave (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    chave_id bigint NOT NULL,
    registrado_por bigint NOT NULL,
    condicao condicao_chave NOT NULL,
    descricao text NOT NULL CHECK (btrim(descricao) <> ''),
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    FOREIGN KEY (chave_id, laboratorio_id) REFERENCES chave(id, laboratorio_id),
    FOREIGN KEY (registrado_por, laboratorio_id) REFERENCES usuario(id, laboratorio_id)
);

CREATE TABLE item_estoque (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    nome text NOT NULL CHECK (btrim(nome) <> ''),
    lote text NOT NULL DEFAULT 'SEM_LOTE' CHECK (btrim(lote) <> ''),
    unidade text NOT NULL CHECK (btrim(unidade) <> ''),
    quantidade numeric(14,4) NOT NULL DEFAULT 0 CHECK (quantidade >= 0 AND quantidade <> 'NaN'::numeric),
    limite_estoque_baixo numeric(14,4) NOT NULL DEFAULT 0 CHECK (limite_estoque_baixo >= 0 AND limite_estoque_baixo <> 'NaN'::numeric),
    validade date,
    ativo boolean NOT NULL DEFAULT true,
    UNIQUE (id, laboratorio_id),
    UNIQUE (laboratorio_id, nome, lote)
);
CREATE TABLE movimentacao_estoque (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    item_id bigint NOT NULL,
    registrado_por bigint NOT NULL,
    variacao numeric(14,4) NOT NULL CHECK (variacao <> 0 AND variacao <> 'NaN'::numeric),
    quantidade_anterior numeric(14,4) NOT NULL CHECK (quantidade_anterior >= 0 AND quantidade_anterior <> 'NaN'::numeric),
    quantidade_posterior numeric(14,4) NOT NULL CHECK (quantidade_posterior >= 0 AND quantidade_posterior <> 'NaN'::numeric),
    motivo text NOT NULL CHECK (btrim(motivo) <> ''),
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (quantidade_posterior = quantidade_anterior + variacao),
    FOREIGN KEY (item_id, laboratorio_id) REFERENCES item_estoque(id, laboratorio_id),
    FOREIGN KEY (registrado_por, laboratorio_id) REFERENCES usuario(id, laboratorio_id)
);
CREATE TABLE protocolo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    titulo text NOT NULL CHECK (btrim(titulo) <> ''),
    autor_id bigint NOT NULL,
    -- Arquivo original preservado no banco: exportação devolve estes mesmos bytes.
    pdf_original bytea NOT NULL CHECK (octet_length(pdf_original) > 5 AND substring(pdf_original FROM 1 FOR 5) = decode('255044462d', 'hex')),
    nome_arquivo text NOT NULL CHECK (lower(nome_arquivo) LIKE '%.pdf'),
    estado estado_protocolo NOT NULL DEFAULT 'NAO_VALIDADO',
    assinado_em timestamptz,
    assinado_por bigint,
    validado_em timestamptz,
    validado_por bigint,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (id, laboratorio_id),
    CHECK ((assinado_em IS NULL) = (assinado_por IS NULL)),
    CHECK (assinado_por IS NULL OR assinado_por = autor_id),
    CHECK (assinado_em IS NULL OR assinado_em >= criado_em),
    CHECK ((estado = 'VALIDADO' AND validado_em IS NOT NULL AND validado_por IS NOT NULL)
        OR (estado = 'NAO_VALIDADO' AND validado_em IS NULL AND validado_por IS NULL)),
    CHECK (validado_em IS NULL OR (assinado_em IS NOT NULL AND validado_em >= assinado_em)),
    FOREIGN KEY (autor_id, laboratorio_id) REFERENCES usuario(id, laboratorio_id),
    FOREIGN KEY (assinado_por, laboratorio_id) REFERENCES usuario(id, laboratorio_id),
    FOREIGN KEY (validado_por, laboratorio_id) REFERENCES chefe_laboratorio(usuario_id, laboratorio_id)
);
CREATE TABLE protocolo_equipamento (
    protocolo_id bigint NOT NULL,
    equipamento_id bigint NOT NULL,
    laboratorio_id bigint NOT NULL,
    vinculado_por bigint NOT NULL,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (protocolo_id, equipamento_id),
    FOREIGN KEY (protocolo_id, laboratorio_id) REFERENCES protocolo(id, laboratorio_id),
    FOREIGN KEY (equipamento_id, laboratorio_id) REFERENCES equipamento(recurso_id, laboratorio_id),
    FOREIGN KEY (vinculado_por, laboratorio_id) REFERENCES chefe_laboratorio(usuario_id, laboratorio_id)
);

CREATE TABLE proibicao_aluno_equipamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    aluno_id bigint NOT NULL,
    equipamento_id bigint NOT NULL,
    motivo text NOT NULL CHECK (btrim(motivo) <> ''),
    aplicada_por bigint NOT NULL,
    criada_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    encerrada_em timestamptz,
    encerrada_por bigint,
    UNIQUE (id, laboratorio_id),
    CHECK ((encerrada_em IS NULL) = (encerrada_por IS NULL)),
    CHECK (encerrada_em IS NULL OR encerrada_em >= criada_em),
    FOREIGN KEY (aluno_id, laboratorio_id) REFERENCES aluno(usuario_id, laboratorio_id),
    FOREIGN KEY (equipamento_id, laboratorio_id) REFERENCES equipamento(recurso_id, laboratorio_id),
    FOREIGN KEY (aplicada_por, laboratorio_id) REFERENCES chefe_laboratorio(usuario_id, laboratorio_id),
    FOREIGN KEY (encerrada_por, laboratorio_id) REFERENCES chefe_laboratorio(usuario_id, laboratorio_id)
);
CREATE UNIQUE INDEX proibicao_ativa_unica ON proibicao_aluno_equipamento(aluno_id, equipamento_id) WHERE encerrada_em IS NULL;
CREATE TABLE solicitacao_reativacao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    proibicao_id bigint NOT NULL,
    solicitado_por bigint NOT NULL,
    justificativa text NOT NULL CHECK (btrim(justificativa) <> ''),
    estado estado_solicitacao NOT NULL DEFAULT 'PENDENTE',
    solicitada_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    respondida_em timestamptz,
    respondida_por bigint,
    resposta text,
    CHECK ((estado <> 'PENDENTE' AND respondida_em IS NOT NULL AND respondida_por IS NOT NULL AND nullif(btrim(resposta), '') IS NOT NULL)
        OR (estado = 'PENDENTE' AND respondida_em IS NULL AND respondida_por IS NULL AND resposta IS NULL)),
    CHECK (respondida_em IS NULL OR respondida_em >= solicitada_em),
    FOREIGN KEY (proibicao_id, laboratorio_id) REFERENCES proibicao_aluno_equipamento(id, laboratorio_id),
    FOREIGN KEY (solicitado_por, laboratorio_id) REFERENCES aluno(usuario_id, laboratorio_id),
    FOREIGN KEY (respondida_por, laboratorio_id) REFERENCES chefe_laboratorio(usuario_id, laboratorio_id)
);
CREATE UNIQUE INDEX solicitacao_aberta_unica ON solicitacao_reativacao(proibicao_id) WHERE estado = 'PENDENTE';
CREATE TABLE ocorrencia (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    autor_id bigint NOT NULL,
    recurso_id bigint,
    item_estoque_id bigint,
    tipo text NOT NULL CHECK (tipo IN ('DANO', 'FALTA_ESTOQUE', 'OUTRO')),
    descricao text NOT NULL CHECK (btrim(descricao) <> ''),
    resolvida_em timestamptz,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (num_nonnulls(recurso_id, item_estoque_id) <= 1),
    FOREIGN KEY (autor_id, laboratorio_id) REFERENCES usuario(id, laboratorio_id),
    FOREIGN KEY (recurso_id, laboratorio_id) REFERENCES recurso(id, laboratorio_id),
    FOREIGN KEY (item_estoque_id, laboratorio_id) REFERENCES item_estoque(id, laboratorio_id)
);

CREATE TABLE notificacao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    destinatario_id bigint NOT NULL,
    tipo text NOT NULL CHECK (btrim(tipo) <> ''),
    mensagem text NOT NULL CHECK (btrim(mensagem) <> ''),
    referencia jsonb NOT NULL DEFAULT '{}',
    chave_deduplicacao text,
    criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    lida_em timestamptz,
    FOREIGN KEY (destinatario_id, laboratorio_id) REFERENCES usuario(id, laboratorio_id)
);
CREATE UNIQUE INDEX notificacao_deduplicada ON notificacao(destinatario_id, chave_deduplicacao) WHERE chave_deduplicacao IS NOT NULL;
CREATE TABLE envio_email (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificacao_id bigint NOT NULL UNIQUE REFERENCES notificacao(id),
    estado estado_envio NOT NULL DEFAULT 'PENDENTE',
    tentativas integer NOT NULL DEFAULT 0 CHECK (tentativas >= 0),
    proxima_tentativa_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    enviado_em timestamptz,
    ultimo_erro text,
    CHECK ((estado = 'ENVIADO') = (enviado_em IS NOT NULL))
);
CREATE TABLE historico_uso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL REFERENCES laboratorio(id),
    ator_id bigint,
    tabela text NOT NULL,
    registro_id text NOT NULL,
    acao text NOT NULL CHECK (acao IN ('INSERT', 'UPDATE', 'DELETE')),
    motivo text,
    antes jsonb,
    depois jsonb,
    registrado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
    transacao_id bigint NOT NULL DEFAULT txid_current(),
    FOREIGN KEY (ator_id, laboratorio_id) REFERENCES usuario(id, laboratorio_id)
);
CREATE TABLE schema_versao (
    versao integer PRIMARY KEY,
    descricao text NOT NULL,
    aplicada_em timestamptz NOT NULL DEFAULT clock_timestamp()
);
INSERT INTO schema_versao(versao, descricao) VALUES (1, 'Modelo relacional inicial, requisitos revisados em 04/10/2026');

CREATE INDEX usuario_laboratorio_idx ON usuario(laboratorio_id);
CREATE UNIQUE INDEX equipamento_patrimonio_normalizado ON equipamento(upper(btrim(numero_patrimonio)));
CREATE UNIQUE INDEX chave_codigo_normalizado ON chave(upper(btrim(codigo_copia)));
CREATE UNIQUE INDEX bancada_identificacao_normalizada ON bancada(sala_id,upper(btrim(numero_identificacao)));
CREATE INDEX aluno_orientador_idx ON aluno(orientador_usuario_id);
CREATE INDEX recurso_laboratorio_idx ON recurso(laboratorio_id);
CREATE INDEX recurso_responsavel_idx ON recurso(responsavel_usuario_id);
CREATE INDEX bancada_sala_idx ON bancada(sala_id);
CREATE INDEX equipamento_bancada_idx ON equipamento(bancada_id);
CREATE INDEX equipamento_sala_idx ON equipamento(sala_direta_id);
CREATE INDEX reserva_usuario_periodo_idx ON reserva(usuario_id, inicio, fim) WHERE bloqueia;
CREATE INDEX reserva_laboratorio_idx ON reserva(laboratorio_id);
CREATE INDEX reserva_principal_idx ON reserva(recurso_principal_id);
CREATE INDEX reserva_recurso_recurso_idx ON reserva_recurso(recurso_id);
CREATE INDEX chave_sala_idx ON chave(sala_id);
CREATE INDEX chave_bancada_idx ON chave(bancada_id);
CREATE INDEX emprestimo_usuario_idx ON emprestimo_chave(usuario_id);
CREATE INDEX emprestimo_reserva_idx ON emprestimo_chave(reserva_id);
CREATE INDEX item_estoque_lab_idx ON item_estoque(laboratorio_id);
CREATE INDEX movimentacao_item_idx ON movimentacao_estoque(item_id, criado_em);
CREATE INDEX protocolo_autor_idx ON protocolo(autor_id);
CREATE INDEX protocolo_equipamento_equip_idx ON protocolo_equipamento(equipamento_id);
CREATE INDEX proibicao_equipamento_idx ON proibicao_aluno_equipamento(equipamento_id) WHERE encerrada_em IS NULL;
CREATE INDEX notificacao_destinatario_idx ON notificacao(destinatario_id, criado_em DESC);
CREATE INDEX envio_email_pendente_idx ON envio_email(proxima_tentativa_em) WHERE estado <> 'ENVIADO';
CREATE INDEX historico_laboratorio_data_idx ON historico_uso(laboratorio_id, registrado_em DESC);
CREATE INDEX historico_ator_data_idx ON historico_uso(ator_id, registrado_em DESC);

COMMENT ON TABLE usuario IS 'Classe abstrata: exatamente uma subclasse Aluno ou Professor, validada ao COMMIT.';
COMMENT ON TABLE chefe_laboratorio IS 'Especialização de Professor; responsável por um laboratório.';
COMMENT ON TABLE reserva_recurso IS 'Abrangência materializada da reserva; intervalo e bloqueio sincronizados por FK. Não criar reservas independentes por equipamento.';
COMMENT ON COLUMN equipamento.numero_patrimonio IS 'Identificador único global da unidade física.';
COMMENT ON COLUMN equipamento.complemento_local IS 'Posição exata dentro da sala ou bancada, por exemplo armário, prateleira ou posição 2.';
COMMENT ON COLUMN chave.designada_para IS 'Decisão de implementação: permite cópia compartilhada ou designada a usuário; política definitiva deve ser validada pelo cliente.';
COMMENT ON TABLE historico_uso IS 'Histórico preservado, com exclusão/alteração bloqueada por trigger. Senhas, tokens e bytes de PDF são removidos dos snapshots.';
COMMENT ON TABLE envio_email IS 'Fila persistente; envio e reenvio via SMTP pertencem ao serviço da aplicação.';
COMMIT;

-- Aplicar depois de 01_schema.sql. Funções de domínio, triggers e consultas.
BEGIN;
SET LOCAL search_path = gestao_lab, public;

CREATE FUNCTION exigir_isolamento() RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('transaction_isolation') <> 'read committed' THEN
        RAISE EXCEPTION 'Operação de domínio exige isolamento READ COMMITTED' USING ERRCODE='25000';
    END IF;
END $$;

CREATE FUNCTION exigir_usuario(p_usuario bigint, p_lab bigint) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM usuario u JOIN laboratorio l ON l.id=u.laboratorio_id
                   WHERE u.id=p_usuario AND u.laboratorio_id=p_lab AND u.ativo AND l.ativo) THEN
        RAISE EXCEPTION 'Usuário inativo ou sem vínculo com o laboratório' USING ERRCODE='42501';
    END IF;
END $$;
CREATE FUNCTION exigir_chefe(p_usuario bigint, p_lab bigint) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    PERFORM exigir_usuario(p_usuario, p_lab);
    IF NOT EXISTS (SELECT 1 FROM laboratorio WHERE id=p_lab AND chefe_usuario_id=p_usuario) THEN
        RAISE EXCEPTION 'Operação exige o Chefe do laboratório' USING ERRCODE='42501';
    END IF;
END $$;
CREATE FUNCTION exigir_gestor_chave(p_usuario bigint, p_recurso bigint, p_lab bigint) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    PERFORM exigir_usuario(p_usuario, p_lab);
    IF NOT EXISTS (SELECT 1 FROM laboratorio WHERE id=p_lab AND chefe_usuario_id=p_usuario)
       AND NOT EXISTS (SELECT 1 FROM recurso WHERE id=p_recurso AND laboratorio_id=p_lab
                       AND responsavel_usuario_id=p_usuario AND tipo IN ('SALA','BANCADA')) THEN
        RAISE EXCEPTION 'Chave exige Chefe ou Professor responsável pelo destino' USING ERRCODE='42501';
    END IF;
END $$;
CREATE FUNCTION contexto_operacao(p_usuario bigint, p_motivo text DEFAULT NULL) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    PERFORM set_config('app.usuario_id', p_usuario::text, true);
    PERFORM set_config('app.motivo', coalesce(p_motivo,''), true);
END $$;

-- Subclasses completas ao COMMIT; permite inserir base e subtipo na mesma transação.
CREATE FUNCTION tg_usuario_subtipo() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_id bigint; v_total integer;
BEGIN
    v_id := CASE WHEN TG_TABLE_NAME='usuario' THEN coalesce((to_jsonb(NEW)->>'id')::bigint,(to_jsonb(OLD)->>'id')::bigint)
                 ELSE coalesce((to_jsonb(NEW)->>'usuario_id')::bigint,(to_jsonb(OLD)->>'usuario_id')::bigint) END;
    IF EXISTS (SELECT 1 FROM usuario WHERE id=v_id) THEN
        SELECT (EXISTS(SELECT 1 FROM aluno WHERE usuario_id=v_id))::integer
             + (EXISTS(SELECT 1 FROM professor WHERE usuario_id=v_id))::integer INTO v_total;
        IF v_total<>1 THEN RAISE EXCEPTION 'Usuário % exige exatamente um subtipo: Aluno ou Professor',v_id USING ERRCODE='23514'; END IF;
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER usuario_subtipo AFTER INSERT OR UPDATE OR DELETE ON usuario DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_usuario_subtipo();
CREATE CONSTRAINT TRIGGER aluno_subtipo AFTER INSERT OR UPDATE OR DELETE ON aluno DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_usuario_subtipo();
CREATE CONSTRAINT TRIGGER professor_subtipo AFTER INSERT OR UPDATE OR DELETE ON professor DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_usuario_subtipo();
CREATE FUNCTION tg_recurso_subtipo() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_id bigint; v_tipo tipo_recurso; v_ok boolean;
BEGIN
    v_id := CASE WHEN TG_TABLE_NAME='recurso' THEN coalesce((to_jsonb(NEW)->>'id')::bigint,(to_jsonb(OLD)->>'id')::bigint)
                 ELSE coalesce((to_jsonb(NEW)->>'recurso_id')::bigint,(to_jsonb(OLD)->>'recurso_id')::bigint) END;
    SELECT tipo INTO v_tipo FROM recurso WHERE id=v_id;
    IF FOUND THEN
        v_ok := CASE v_tipo WHEN 'SALA' THEN EXISTS(SELECT 1 FROM sala WHERE recurso_id=v_id)
                  WHEN 'BANCADA' THEN EXISTS(SELECT 1 FROM bancada WHERE recurso_id=v_id)
                  ELSE EXISTS(SELECT 1 FROM equipamento WHERE recurso_id=v_id) END;
        IF NOT v_ok THEN RAISE EXCEPTION 'Recurso % sem subclasse % correspondente',v_id,v_tipo USING ERRCODE='23514'; END IF;
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER recurso_subtipo AFTER INSERT OR UPDATE OR DELETE ON recurso DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_recurso_subtipo();
CREATE CONSTRAINT TRIGGER sala_subtipo AFTER INSERT OR UPDATE OR DELETE ON sala DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_recurso_subtipo();
CREATE CONSTRAINT TRIGGER bancada_subtipo AFTER INSERT OR UPDATE OR DELETE ON bancada DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_recurso_subtipo();
CREATE CONSTRAINT TRIGGER equipamento_subtipo AFTER INSERT OR UPDATE OR DELETE ON equipamento DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_recurso_subtipo();

CREATE VIEW vw_local_recurso AS
SELECT r.id recurso_id, r.laboratorio_id, l.nome laboratorio_nome, r.tipo, r.nome recurso_nome, r.estado,
       CASE r.tipo WHEN 'SALA' THEN r.id WHEN 'BANCADA' THEN b.sala_id ELSE coalesce(e.sala_direta_id, eb.sala_id) END sala_id,
       sr.nome sala_nome, s.identificacao sala_identificacao, s.localizacao sala_localizacao,
       CASE WHEN r.tipo='BANCADA' THEN r.id ELSE e.bancada_id END bancada_id,
       br.nome bancada_nome, coalesce(b.numero_identificacao,eb.numero_identificacao) bancada_identificacao,
       e.numero_patrimonio, e.complemento_local
FROM recurso r JOIN laboratorio l ON l.id=r.laboratorio_id
LEFT JOIN bancada b ON b.recurso_id=r.id
LEFT JOIN equipamento e ON e.recurso_id=r.id
LEFT JOIN bancada eb ON eb.recurso_id=e.bancada_id
LEFT JOIN sala s ON s.recurso_id=CASE r.tipo WHEN 'SALA' THEN r.id WHEN 'BANCADA' THEN b.sala_id ELSE coalesce(e.sala_direta_id,eb.sala_id) END
LEFT JOIN recurso sr ON sr.id=s.recurso_id
LEFT JOIN recurso br ON br.id=CASE WHEN r.tipo='BANCADA' THEN r.id ELSE e.bancada_id END;
CREATE VIEW vw_local_equipamento AS SELECT * FROM vw_local_recurso WHERE tipo='EQUIPAMENTO';
CREATE FUNCTION recursos_abrangidos(p_recurso bigint) RETURNS TABLE(recurso_id bigint)
LANGUAGE sql STABLE SET search_path = gestao_lab, public AS $$
    SELECT r.id FROM recurso r WHERE r.id=p_recurso
    UNION
    SELECT b.recurso_id FROM bancada b WHERE b.sala_id=p_recurso
    UNION
    SELECT e.recurso_id FROM equipamento e LEFT JOIN bancada b ON b.recurso_id=e.bancada_id
    WHERE e.bancada_id=p_recurso OR e.sala_direta_id=p_recurso OR b.sala_id=p_recurso
$$;
CREATE FUNCTION recursos_ancestrais(p_recurso bigint) RETURNS TABLE(recurso_id bigint)
LANGUAGE sql STABLE SET search_path = gestao_lab, public AS $$
    SELECT p_recurso
    UNION SELECT sala_id FROM vw_local_recurso WHERE recurso_id=p_recurso AND sala_id IS NOT NULL
    UNION SELECT bancada_id FROM vw_local_recurso WHERE recurso_id=p_recurso AND bancada_id IS NOT NULL
$$;
CREATE FUNCTION recurso_disponivel(p_recurso bigint, p_inicio timestamptz, p_fim timestamptz) RETURNS boolean
LANGUAGE sql STABLE SET search_path = gestao_lab, public AS $$
    SELECT p_inicio < p_fim
       AND EXISTS(SELECT 1 FROM recurso WHERE id=p_recurso)
       AND NOT EXISTS(SELECT 1 FROM recursos_abrangidos(p_recurso) a
                      CROSS JOIN LATERAL recursos_ancestrais(a.recurso_id) c JOIN recurso r ON r.id=c.recurso_id
                      WHERE r.estado<>'DISPONIVEL')
       AND NOT EXISTS(SELECT 1 FROM reserva_recurso rr JOIN recursos_abrangidos(p_recurso) a USING(recurso_id)
                      WHERE rr.bloqueia AND rr.periodo && tstzrange(p_inicio,p_fim,'[)'))
$$;

CREATE FUNCTION tg_validar_reserva() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab laboratorio%ROWTYPE; v_pico integer;
BEGIN
    -- Um lock por laboratório mantém coerentes limites, composição e alterações concorrentes.
    PERFORM exigir_isolamento();
    SELECT * INTO STRICT v_lab FROM laboratorio WHERE id=NEW.laboratorio_id FOR UPDATE;
    IF TG_OP='UPDATE' THEN
        IF (NEW.id,NEW.laboratorio_id,NEW.usuario_id,NEW.recurso_principal_id,NEW.inicio,NEW.fim,NEW.criado_em)
           IS DISTINCT FROM (OLD.id,OLD.laboratorio_id,OLD.usuario_id,OLD.recurso_principal_id,OLD.inicio,OLD.fim,OLD.criado_em) THEN
            RAISE EXCEPTION 'Reserva imutável: cancelar e criar outra para alterar recurso ou período' USING ERRCODE='23514';
        END IF;
        IF OLD.estado<>'CONFIRMADA' AND NEW IS DISTINCT FROM OLD THEN
            RAISE EXCEPTION 'Reserva encerrada não pode ser alterada' USING ERRCODE='23514';
        END IF;
        IF NEW.estado='CANCELADA' AND OLD.estado='CONFIRMADA' THEN
            PERFORM exigir_usuario(NEW.cancelado_por,NEW.laboratorio_id);
            IF NEW.cancelado_por<>NEW.usuario_id AND NEW.cancelado_por<>v_lab.chefe_usuario_id THEN
                RAISE EXCEPTION 'Somente o dono ou Chefe pode cancelar' USING ERRCODE='42501';
            END IF;
        ELSIF NEW.estado='CONCLUIDA' AND clock_timestamp()<NEW.fim THEN
            RAISE EXCEPTION 'Conclusão somente após o fim da reserva' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    PERFORM exigir_usuario(NEW.usuario_id,NEW.laboratorio_id);
    IF NEW.estado<>'CONFIRMADA' THEN RAISE EXCEPTION 'Nova reserva deve ser CONFIRMADA' USING ERRCODE='23514'; END IF;
    IF NOT isfinite(NEW.inicio) OR NOT isfinite(NEW.fim) OR NEW.fim<=NEW.inicio THEN
        RAISE EXCEPTION 'Período inválido' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS(SELECT 1 FROM recurso WHERE id=NEW.recurso_principal_id AND laboratorio_id=NEW.laboratorio_id) THEN
        RAISE EXCEPTION 'Recurso de outro laboratório ou inexistente' USING ERRCODE='23503';
    END IF;
    IF v_lab.duracao_maxima_reserva IS NOT NULL AND NEW.fim-NEW.inicio>v_lab.duracao_maxima_reserva THEN
        RAISE EXCEPTION 'Duração excede o limite do laboratório' USING ERRCODE='23514';
    END IF;
    IF EXISTS(SELECT 1 FROM recursos_abrangidos(NEW.recurso_principal_id) a
              CROSS JOIN LATERAL recursos_ancestrais(a.recurso_id) c JOIN recurso r ON r.id=c.recurso_id
              WHERE r.estado<>'DISPONIVEL') THEN
        RAISE EXCEPTION 'Conjunto contém recurso ou local indisponível' USING ERRCODE='23514';
    END IF;
    IF EXISTS(SELECT 1 FROM proibicao_aluno_equipamento p JOIN recursos_abrangidos(NEW.recurso_principal_id) a ON a.recurso_id=p.equipamento_id
              WHERE p.aluno_id=NEW.usuario_id AND p.encerrada_em IS NULL) THEN
        RAISE EXCEPTION 'Aluno proibido de utilizar equipamento abrangido' USING ERRCODE='42501';
    END IF;
    IF v_lab.max_reservas_simultaneas IS NOT NULL THEN
        -- Pico real por usuário: não soma duas reservas consecutivas como simultâneas.
        WITH eventos AS (
            SELECT greatest(inicio,NEW.inicio) instante,1 delta FROM reserva
            WHERE usuario_id=NEW.usuario_id AND bloqueia AND periodo && tstzrange(NEW.inicio,NEW.fim,'[)')
            UNION ALL
            SELECT least(fim,NEW.fim),-1 FROM reserva
            WHERE usuario_id=NEW.usuario_id AND bloqueia AND periodo && tstzrange(NEW.inicio,NEW.fim,'[)')
        ), agrupados AS (SELECT instante,sum(delta) delta FROM eventos GROUP BY instante),
        acumulados AS (SELECT sum(delta) OVER(ORDER BY instante) qtd FROM agrupados)
        SELECT coalesce(max(qtd),0)::integer INTO v_pico FROM acumulados;
        IF v_pico+1>v_lab.max_reservas_simultaneas THEN
            RAISE EXCEPTION 'Quantidade simultânea excede o limite por usuário' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER validar_reserva BEFORE INSERT OR UPDATE ON reserva FOR EACH ROW EXECUTE FUNCTION tg_validar_reserva();
CREATE FUNCTION tg_materializar_abrangencia() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    INSERT INTO reserva_recurso(reserva_id,recurso_id,laboratorio_id,periodo,bloqueia,local_registrado)
    SELECT NEW.id,a.recurso_id,NEW.laboratorio_id,NEW.periodo,NEW.bloqueia,to_jsonb(v)
    FROM recursos_abrangidos(NEW.recurso_principal_id) a JOIN vw_local_recurso v USING(recurso_id);
    RETURN NEW;
END $$;
CREATE TRIGGER materializar_abrangencia AFTER INSERT ON reserva FOR EACH ROW EXECUTE FUNCTION tg_materializar_abrangencia();
CREATE FUNCTION tg_abrangencia_origem() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF pg_trigger_depth()<2 THEN
        RAISE EXCEPTION 'Abrangência é gerada automaticamente ao criar a reserva' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER abrangencia_origem BEFORE INSERT ON reserva_recurso FOR EACH ROW EXECUTE FUNCTION tg_abrangencia_origem();
CREATE FUNCTION tg_conferir_abrangencia() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_id bigint; v_principal bigint; v_estado estado_reserva;
BEGIN
    v_id:=CASE WHEN TG_TABLE_NAME='reserva' THEN coalesce((to_jsonb(NEW)->>'id')::bigint,(to_jsonb(OLD)->>'id')::bigint)
               ELSE coalesce((to_jsonb(NEW)->>'reserva_id')::bigint,(to_jsonb(OLD)->>'reserva_id')::bigint) END;
    SELECT recurso_principal_id,estado INTO v_principal,v_estado FROM reserva WHERE id=v_id;
    -- Reserva histórica preserva composição original, mesmo após movimentações futuras.
    IF FOUND AND v_estado='CONFIRMADA' AND EXISTS(SELECT 1 FROM reserva WHERE id=v_id AND fim>clock_timestamp()) THEN
        IF EXISTS((SELECT recurso_id FROM recursos_abrangidos(v_principal) EXCEPT SELECT recurso_id FROM reserva_recurso WHERE reserva_id=v_id)
                  UNION ALL
                  (SELECT recurso_id FROM reserva_recurso WHERE reserva_id=v_id EXCEPT SELECT recurso_id FROM recursos_abrangidos(v_principal))) THEN
            RAISE EXCEPTION 'Abrangência incompleta ou divergente da reserva %',v_id USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER conferir_reserva AFTER INSERT OR UPDATE ON reserva DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_conferir_abrangencia();
CREATE CONSTRAINT TRIGGER conferir_reserva_recurso AFTER INSERT OR UPDATE OR DELETE ON reserva_recurso DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION tg_conferir_abrangencia();
CREATE FUNCTION tg_abrangencia_imutavel() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.reserva_id,NEW.recurso_id,NEW.laboratorio_id,NEW.local_registrado)
       IS DISTINCT FROM (OLD.reserva_id,OLD.recurso_id,OLD.laboratorio_id,OLD.local_registrado) THEN
        RAISE EXCEPTION 'Identidade e local histórico da abrangência são imutáveis' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER abrangencia_imutavel BEFORE UPDATE ON reserva_recurso FOR EACH ROW EXECUTE FUNCTION tg_abrangencia_imutavel();

CREATE FUNCTION notificar(p_lab bigint,p_destinatario bigint,p_tipo text,p_mensagem text,p_referencia jsonb DEFAULT '{}',p_dedup text DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_id bigint;
BEGIN
    INSERT INTO notificacao(laboratorio_id,destinatario_id,tipo,mensagem,referencia,chave_deduplicacao)
    VALUES(p_lab,p_destinatario,p_tipo,p_mensagem,p_referencia,p_dedup) ON CONFLICT DO NOTHING RETURNING id INTO v_id;
    IF v_id IS NOT NULL THEN INSERT INTO envio_email(notificacao_id) VALUES(v_id); END IF;
    RETURN v_id;
END $$;
CREATE FUNCTION criar_reserva(p_usuario bigint,p_recurso bigint,p_inicio timestamptz,p_fim timestamptz) RETURNS bigint
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_id bigint; v_lab bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM recurso WHERE id=p_recurso;
    PERFORM contexto_operacao(p_usuario);
    INSERT INTO reserva(laboratorio_id,usuario_id,recurso_principal_id,inicio,fim)
    VALUES(v_lab,p_usuario,p_recurso,p_inicio,p_fim) RETURNING id INTO v_id;
    RETURN v_id;
END $$;
CREATE FUNCTION cancelar_reserva(p_ator bigint,p_reserva bigint,p_motivo text) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint; v_usuario bigint;
BEGIN
    IF nullif(btrim(p_motivo),'') IS NULL THEN RAISE EXCEPTION 'Informe motivo de cancelamento' USING ERRCODE='23514'; END IF;
    SELECT laboratorio_id,usuario_id INTO STRICT v_lab,v_usuario FROM reserva WHERE id=p_reserva;
    PERFORM 1 FROM laboratorio WHERE id=v_lab FOR UPDATE;
    PERFORM contexto_operacao(p_ator,p_motivo);
    UPDATE reserva SET estado='CANCELADA',cancelado_em=clock_timestamp(),cancelado_por=p_ator,motivo_cancelamento=p_motivo
    WHERE id=p_reserva AND estado='CONFIRMADA';
    IF NOT FOUND THEN RAISE EXCEPTION 'Reserva não está confirmada' USING ERRCODE='23514'; END IF;
    PERFORM notificar(v_lab,v_usuario,'RESERVA_CANCELADA',p_motivo,jsonb_build_object('reserva_id',p_reserva));
    -- Não altera nem encerra empréstimos de chave.
END $$;

CREATE FUNCTION tg_guardar_local() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint; v_ids bigint[]; v_row jsonb; v_old jsonb;
BEGIN
    v_row:=to_jsonb(NEW); v_old:=to_jsonb(OLD);
    PERFORM exigir_isolamento();
    v_lab:=coalesce((v_row->>'laboratorio_id')::bigint,(v_old->>'laboratorio_id')::bigint);
    PERFORM 1 FROM laboratorio WHERE id=v_lab FOR UPDATE;
    IF TG_OP='UPDATE' AND (NEW.recurso_id,NEW.laboratorio_id) IS DISTINCT FROM (OLD.recurso_id,OLD.laboratorio_id) THEN
        RAISE EXCEPTION 'Identidade e laboratório de subtipo são imutáveis' USING ERRCODE='23514';
    END IF;
    IF TG_TABLE_NAME='equipamento' THEN
        IF TG_OP='UPDATE' AND (NEW.bancada_id,NEW.sala_direta_id,NEW.complemento_local)
           IS NOT DISTINCT FROM (OLD.bancada_id,OLD.sala_direta_id,OLD.complemento_local) THEN RETURN NEW; END IF;
        SELECT array_agg(DISTINCT id) INTO v_ids FROM (
            SELECT coalesce((v_row->>'recurso_id')::bigint,(v_old->>'recurso_id')::bigint) id
            UNION SELECT (v_row->>'bancada_id')::bigint UNION SELECT (v_old->>'bancada_id')::bigint
            UNION SELECT (v_row->>'sala_direta_id')::bigint UNION SELECT (v_old->>'sala_direta_id')::bigint
            UNION SELECT sala_id FROM bancada WHERE recurso_id IN ((v_row->>'bancada_id')::bigint,(v_old->>'bancada_id')::bigint)
        ) q;
    ELSIF TG_TABLE_NAME='bancada' THEN
        IF TG_OP='UPDATE' AND (NEW.sala_id,NEW.numero_identificacao) IS NOT DISTINCT FROM (OLD.sala_id,OLD.numero_identificacao) THEN RETURN NEW; END IF;
        SELECT array_agg(DISTINCT id) INTO v_ids FROM (
            SELECT coalesce((v_row->>'recurso_id')::bigint,(v_old->>'recurso_id')::bigint) id
            UNION SELECT (v_row->>'sala_id')::bigint UNION SELECT (v_old->>'sala_id')::bigint
            UNION SELECT recurso_id FROM equipamento WHERE bancada_id=coalesce((v_row->>'recurso_id')::bigint,(v_old->>'recurso_id')::bigint)
        ) q;
    ELSE
        IF TG_OP='UPDATE' AND (NEW.identificacao,NEW.localizacao,NEW.capacidade) IS NOT DISTINCT FROM (OLD.identificacao,OLD.localizacao,OLD.capacidade) THEN RETURN NEW; END IF;
        SELECT array_agg(recurso_id) INTO v_ids FROM recursos_abrangidos(coalesce((v_row->>'recurso_id')::bigint,(v_old->>'recurso_id')::bigint));
    END IF;
    IF EXISTS(SELECT 1 FROM reserva_recurso rr JOIN reserva r ON r.id=rr.reserva_id
              WHERE rr.recurso_id=ANY(v_ids) AND r.bloqueia AND r.fim>clock_timestamp()) THEN
        RAISE EXCEPTION 'Local ou composição possui reserva vigente/futura; regularize antes da alteração' USING ERRCODE='23514';
    END IF;
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER guardar_local_sala BEFORE INSERT OR UPDATE OR DELETE ON sala FOR EACH ROW EXECUTE FUNCTION tg_guardar_local();
CREATE TRIGGER guardar_local_bancada BEFORE INSERT OR UPDATE OR DELETE ON bancada FOR EACH ROW EXECUTE FUNCTION tg_guardar_local();
CREATE TRIGGER guardar_local_equipamento BEFORE INSERT OR UPDATE OR DELETE ON equipamento FOR EACH ROW EXECUTE FUNCTION tg_guardar_local();
CREATE FUNCTION alterar_local_equipamento(p_chefe bigint,p_equipamento bigint,p_bancada bigint,p_sala_direta bigint,p_complemento text) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM equipamento WHERE recurso_id=p_equipamento;
    PERFORM 1 FROM laboratorio WHERE id=v_lab FOR UPDATE;
    PERFORM exigir_chefe(p_chefe,v_lab);
    PERFORM contexto_operacao(p_chefe,'Alteração de localização de equipamento');
    UPDATE equipamento SET bancada_id=p_bancada,sala_direta_id=p_sala_direta,complemento_local=p_complemento WHERE recurso_id=p_equipamento;
END $$;
CREATE FUNCTION tg_estado_recurso() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_reserva record; v_ator bigint; v_motivo text;
BEGIN
    PERFORM exigir_isolamento();
    PERFORM 1 FROM laboratorio WHERE id=NEW.laboratorio_id FOR UPDATE;
    IF (NEW.id,NEW.laboratorio_id,NEW.tipo) IS DISTINCT FROM (OLD.id,OLD.laboratorio_id,OLD.tipo) THEN
        RAISE EXCEPTION 'Identidade, laboratório e tipo de recurso são imutáveis' USING ERRCODE='23514';
    END IF;
    IF NEW.estado IS DISTINCT FROM OLD.estado THEN
        v_ator:=nullif(current_setting('app.usuario_id',true),'')::bigint;
        v_motivo:=nullif(current_setting('app.motivo',true),'');
        PERFORM exigir_chefe(v_ator,NEW.laboratorio_id);
        IF v_motivo IS NULL THEN RAISE EXCEPTION 'Mudança de estado exige motivo' USING ERRCODE='23514'; END IF;
        IF NEW.estado<>'DISPONIVEL' THEN
            FOR v_reserva IN SELECT DISTINCT r.id FROM reserva r JOIN reserva_recurso rr ON rr.reserva_id=r.id
                JOIN recursos_abrangidos(NEW.id) a ON a.recurso_id=rr.recurso_id
                WHERE r.bloqueia AND r.fim>clock_timestamp() ORDER BY r.id LOOP
                PERFORM cancelar_reserva(v_ator,v_reserva.id,'Recurso indisponível: '||v_motivo);
            END LOOP;
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER estado_recurso BEFORE UPDATE ON recurso FOR EACH ROW EXECUTE FUNCTION tg_estado_recurso();
CREATE FUNCTION definir_estado_recurso(p_chefe bigint,p_recurso bigint,p_estado estado_recurso,p_motivo text) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM recurso WHERE id=p_recurso;
    PERFORM 1 FROM laboratorio WHERE id=v_lab FOR UPDATE;
    PERFORM exigir_chefe(p_chefe,v_lab);
    PERFORM contexto_operacao(p_chefe,p_motivo);
    UPDATE recurso SET estado=p_estado WHERE id=p_recurso;
END $$;

CREATE VIEW vw_chave_estado AS
SELECT c.*, CASE WHEN c.condicao='EXTRAVIADA' THEN 'EXTRAVIADA'
                 WHEN c.condicao='INDISPONIVEL' THEN 'INDISPONIVEL'
                 WHEN ec.id IS NOT NULL THEN 'EM_USO' ELSE 'DISPONIVEL' END estado,
       ec.id emprestimo_aberto_id,ec.usuario_id portador_usuario_id,ec.retirada_em
FROM chave c LEFT JOIN emprestimo_chave ec ON ec.chave_id=c.id AND ec.devolucao_em IS NULL;
CREATE FUNCTION tg_validar_chave() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    PERFORM exigir_isolamento();
    PERFORM 1 FROM laboratorio WHERE id=NEW.laboratorio_id FOR UPDATE;
    PERFORM exigir_gestor_chave(NEW.designada_por,coalesce(NEW.sala_id,NEW.bancada_id),NEW.laboratorio_id);
    IF TG_OP='UPDATE' THEN
        IF NEW.condicao IS DISTINCT FROM OLD.condicao AND pg_trigger_depth()<2 THEN
            RAISE EXCEPTION 'Condição de chave exige registro de ocorrência' USING ERRCODE='23514';
        END IF;
        IF (NEW.id,NEW.laboratorio_id) IS DISTINCT FROM (OLD.id,OLD.laboratorio_id) THEN
            RAISE EXCEPTION 'Identidade de cópia é imutável' USING ERRCODE='23514';
        END IF;
        IF EXISTS(SELECT 1 FROM emprestimo_chave WHERE chave_id=OLD.id AND devolucao_em IS NULL)
           AND (NEW.sala_id,NEW.bancada_id,NEW.designada_para,NEW.codigo_copia)
               IS DISTINCT FROM (OLD.sala_id,OLD.bancada_id,OLD.designada_para,OLD.codigo_copia) THEN
            RAISE EXCEPTION 'Não alterar designação de cópia emprestada' USING ERRCODE='23514';
        END IF;
        IF (NEW.sala_id,NEW.bancada_id) IS DISTINCT FROM (OLD.sala_id,OLD.bancada_id)
           AND EXISTS(SELECT 1 FROM emprestimo_chave WHERE chave_id=OLD.id) THEN
            RAISE EXCEPTION 'Destino de cópia com histórico é imutável; cadastre outra cópia' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER validar_chave BEFORE INSERT OR UPDATE ON chave FOR EACH ROW EXECUTE FUNCTION tg_validar_chave();
CREATE FUNCTION tg_validar_emprestimo() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_chave chave%ROWTYPE; v_reserva reserva%ROWTYPE;
BEGIN
    PERFORM exigir_isolamento();
    PERFORM 1 FROM laboratorio WHERE id=NEW.laboratorio_id FOR UPDATE;
    SELECT * INTO STRICT v_chave FROM chave WHERE id=NEW.chave_id FOR UPDATE;
    IF TG_OP='UPDATE' THEN
        IF (NEW.id,NEW.laboratorio_id,NEW.chave_id,NEW.usuario_id,NEW.reserva_id,NEW.retirada_em,NEW.entregue_por)
           IS DISTINCT FROM (OLD.id,OLD.laboratorio_id,OLD.chave_id,OLD.usuario_id,OLD.reserva_id,OLD.retirada_em,OLD.entregue_por)
           OR OLD.devolucao_em IS NOT NULL THEN
            RAISE EXCEPTION 'Empréstimo histórico é imutável; somente devolução do aberto é permitida' USING ERRCODE='23514';
        END IF;
        IF NEW.devolucao_em IS NULL THEN RAISE EXCEPTION 'Atualização exige devolução física' USING ERRCODE='23514'; END IF;
        PERFORM exigir_gestor_chave(NEW.recebido_por,coalesce(v_chave.sala_id,v_chave.bancada_id),NEW.laboratorio_id);
        RETURN NEW;
    END IF;
    IF NEW.devolucao_em IS NOT NULL THEN RAISE EXCEPTION 'Novo empréstimo deve permanecer aberto' USING ERRCODE='23514'; END IF;
    PERFORM exigir_usuario(NEW.usuario_id,NEW.laboratorio_id);
    PERFORM exigir_gestor_chave(NEW.entregue_por,coalesce(v_chave.sala_id,v_chave.bancada_id),NEW.laboratorio_id);
    SELECT * INTO STRICT v_reserva FROM reserva WHERE id=NEW.reserva_id;
    IF v_reserva.usuario_id<>NEW.usuario_id OR v_reserva.laboratorio_id<>NEW.laboratorio_id
       OR v_reserva.estado<>'CONFIRMADA' OR v_reserva.fim<=clock_timestamp() OR NEW.retirada_em>=v_reserva.fim THEN
        RAISE EXCEPTION 'Reserva não autoriza a retirada para este usuário' USING ERRCODE='42501';
    END IF;
    IF v_chave.condicao<>'OPERACIONAL' THEN RAISE EXCEPTION 'Cópia indisponível ou extraviada' USING ERRCODE='23514'; END IF;
    IF v_chave.designada_para IS NOT NULL AND v_chave.designada_para<>NEW.usuario_id THEN
        RAISE EXCEPTION 'Cópia designada a outro usuário' USING ERRCODE='42501';
    END IF;
    IF NOT EXISTS(SELECT 1 FROM reserva_recurso rr CROSS JOIN LATERAL recursos_ancestrais(rr.recurso_id) a
                  WHERE rr.reserva_id=NEW.reserva_id AND a.recurso_id=coalesce(v_chave.sala_id,v_chave.bancada_id)) THEN
        RAISE EXCEPTION 'Chave não corresponde ao acesso da reserva' USING ERRCODE='42501';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER validar_emprestimo BEFORE INSERT OR UPDATE ON emprestimo_chave FOR EACH ROW EXECUTE FUNCTION tg_validar_emprestimo();
CREATE FUNCTION retirar_chave(p_usuario bigint,p_reserva bigint,p_chave bigint,p_entregue_por bigint) RETURNS bigint
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_id bigint; v_lab bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM chave WHERE id=p_chave;
    PERFORM 1 FROM laboratorio WHERE id=v_lab FOR UPDATE;
    PERFORM contexto_operacao(p_entregue_por,'Retirada física de chave');
    INSERT INTO emprestimo_chave(laboratorio_id,chave_id,usuario_id,reserva_id,entregue_por)
    VALUES(v_lab,p_chave,p_usuario,p_reserva,p_entregue_por) RETURNING id INTO v_id;
    RETURN v_id;
END $$;
CREATE FUNCTION devolver_chave(p_emprestimo bigint,p_recebido_por bigint) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM emprestimo_chave WHERE id=p_emprestimo;
    PERFORM 1 FROM laboratorio WHERE id=v_lab FOR UPDATE;
    PERFORM contexto_operacao(p_recebido_por,'Devolução física de chave');
    UPDATE emprestimo_chave SET devolucao_em=clock_timestamp(),recebido_por=p_recebido_por
    WHERE id=p_emprestimo AND devolucao_em IS NULL;
    IF NOT FOUND THEN RAISE EXCEPTION 'Empréstimo já encerrado' USING ERRCODE='23514'; END IF;
END $$;
CREATE FUNCTION registrar_ocorrencia_chave(p_gestor bigint,p_chave bigint,p_condicao condicao_chave,p_descricao text) RETURNS bigint
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_chave chave%ROWTYPE; v_id bigint;
BEGIN
    SELECT * INTO STRICT v_chave FROM chave WHERE id=p_chave;
    PERFORM 1 FROM laboratorio WHERE id=v_chave.laboratorio_id FOR UPDATE;
    PERFORM exigir_gestor_chave(p_gestor,coalesce(v_chave.sala_id,v_chave.bancada_id),v_chave.laboratorio_id);
    PERFORM contexto_operacao(p_gestor,p_descricao);
    INSERT INTO ocorrencia_chave(laboratorio_id,chave_id,registrado_por,condicao,descricao)
    VALUES(v_chave.laboratorio_id,p_chave,p_gestor,p_condicao,p_descricao) RETURNING id INTO v_id;
    RETURN v_id;
END $$;
CREATE FUNCTION tg_efeito_ocorrencia_chave() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_chave chave%ROWTYPE;
BEGIN
    PERFORM exigir_isolamento();
    PERFORM 1 FROM laboratorio WHERE id=NEW.laboratorio_id FOR UPDATE;
    SELECT * INTO STRICT v_chave FROM chave WHERE id=NEW.chave_id FOR UPDATE;
    PERFORM exigir_gestor_chave(NEW.registrado_por,coalesce(v_chave.sala_id,v_chave.bancada_id),NEW.laboratorio_id);
    UPDATE chave SET condicao=NEW.condicao,designada_por=NEW.registrado_por WHERE id=NEW.chave_id;
    RETURN NEW;
END $$;
CREATE TRIGGER efeito_ocorrencia_chave AFTER INSERT ON ocorrencia_chave FOR EACH ROW EXECUTE FUNCTION tg_efeito_ocorrencia_chave();

CREATE FUNCTION tg_validar_proibicao() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_reserva record;
BEGIN
    PERFORM exigir_isolamento();
    PERFORM 1 FROM laboratorio WHERE id=NEW.laboratorio_id FOR UPDATE;
    IF TG_OP='UPDATE' THEN
        IF (NEW.id,NEW.laboratorio_id,NEW.aluno_id,NEW.equipamento_id,NEW.motivo,NEW.aplicada_por,NEW.criada_em)
           IS DISTINCT FROM (OLD.id,OLD.laboratorio_id,OLD.aluno_id,OLD.equipamento_id,OLD.motivo,OLD.aplicada_por,OLD.criada_em)
           OR OLD.encerrada_em IS NOT NULL THEN
            RAISE EXCEPTION 'Proibição histórica é imutável' USING ERRCODE='23514';
        END IF;
        IF NEW.encerrada_em IS NOT NULL AND NOT EXISTS(SELECT 1 FROM solicitacao_reativacao
            WHERE proibicao_id=NEW.id AND estado='APROVADA' AND respondida_por=NEW.encerrada_por) THEN
            RAISE EXCEPTION 'Somente aprovação de reativação encerra a proibição' USING ERRCODE='23514';
        END IF;
    ELSE
        PERFORM exigir_chefe(NEW.aplicada_por,NEW.laboratorio_id);
        IF NEW.encerrada_em IS NOT NULL THEN RAISE EXCEPTION 'Nova proibição deve estar ativa' USING ERRCODE='23514'; END IF;
        PERFORM contexto_operacao(NEW.aplicada_por,NEW.motivo);
        FOR v_reserva IN SELECT r.id FROM reserva r JOIN reserva_recurso rr ON rr.reserva_id=r.id
            WHERE r.usuario_id=NEW.aluno_id AND r.bloqueia AND r.fim>clock_timestamp()
              AND rr.recurso_id=NEW.equipamento_id ORDER BY r.id LOOP
            PERFORM cancelar_reserva(NEW.aplicada_por,v_reserva.id,'Proibição de uso: '||NEW.motivo);
        END LOOP;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER validar_proibicao BEFORE INSERT OR UPDATE ON proibicao_aluno_equipamento FOR EACH ROW EXECUTE FUNCTION tg_validar_proibicao();
CREATE FUNCTION proibir_aluno(p_chefe bigint,p_aluno bigint,p_equipamento bigint,p_motivo text) RETURNS bigint
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint; v_id bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM equipamento WHERE recurso_id=p_equipamento;
    PERFORM 1 FROM laboratorio WHERE id=v_lab FOR UPDATE;
    PERFORM contexto_operacao(p_chefe,p_motivo);
    INSERT INTO proibicao_aluno_equipamento(laboratorio_id,aluno_id,equipamento_id,motivo,aplicada_por)
    VALUES(v_lab,p_aluno,p_equipamento,p_motivo,p_chefe) RETURNING id INTO v_id;
    RETURN v_id;
END $$;
CREATE FUNCTION tg_validar_reativacao() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_p proibicao_aluno_equipamento%ROWTYPE;
BEGIN
    PERFORM exigir_isolamento();
    PERFORM 1 FROM laboratorio WHERE id=NEW.laboratorio_id FOR UPDATE;
    SELECT * INTO STRICT v_p FROM proibicao_aluno_equipamento WHERE id=NEW.proibicao_id;
    IF v_p.aluno_id<>NEW.solicitado_por OR v_p.laboratorio_id<>NEW.laboratorio_id OR v_p.encerrada_em IS NOT NULL THEN
        RAISE EXCEPTION 'Pedido deve pertencer ao aluno com proibição ativa' USING ERRCODE='42501';
    END IF;
    IF TG_OP='INSERT' THEN
        PERFORM exigir_usuario(NEW.solicitado_por,NEW.laboratorio_id);
        IF NEW.estado<>'PENDENTE' THEN RAISE EXCEPTION 'Pedido começa pendente' USING ERRCODE='23514'; END IF;
    ELSE
        IF (NEW.id,NEW.laboratorio_id,NEW.proibicao_id,NEW.solicitado_por,NEW.justificativa,NEW.solicitada_em)
           IS DISTINCT FROM (OLD.id,OLD.laboratorio_id,OLD.proibicao_id,OLD.solicitado_por,OLD.justificativa,OLD.solicitada_em)
           OR OLD.estado<>'PENDENTE' OR NEW.estado='PENDENTE' THEN
            RAISE EXCEPTION 'Somente resposta de pedido pendente é permitida' USING ERRCODE='23514';
        END IF;
        PERFORM exigir_chefe(NEW.respondida_por,NEW.laboratorio_id);
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER validar_reativacao BEFORE INSERT OR UPDATE ON solicitacao_reativacao FOR EACH ROW EXECUTE FUNCTION tg_validar_reativacao();
CREATE FUNCTION tg_efeito_reativacao() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_chefe bigint;
BEGIN
    SELECT chefe_usuario_id INTO v_chefe FROM laboratorio WHERE id=NEW.laboratorio_id;
    IF TG_OP='INSERT' THEN
        PERFORM notificar(NEW.laboratorio_id,v_chefe,'REATIVACAO_SOLICITADA',NEW.justificativa,jsonb_build_object('solicitacao_id',NEW.id));
    ELSE
        IF NEW.estado='APROVADA' THEN
            UPDATE proibicao_aluno_equipamento SET encerrada_em=NEW.respondida_em,encerrada_por=NEW.respondida_por WHERE id=NEW.proibicao_id;
        END IF;
        PERFORM notificar(NEW.laboratorio_id,NEW.solicitado_por,'REATIVACAO_RESPONDIDA',NEW.resposta,jsonb_build_object('solicitacao_id',NEW.id,'estado',NEW.estado));
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER efeito_reativacao AFTER INSERT OR UPDATE ON solicitacao_reativacao FOR EACH ROW EXECUTE FUNCTION tg_efeito_reativacao();
CREATE FUNCTION solicitar_reativacao(p_aluno bigint,p_proibicao bigint,p_justificativa text) RETURNS bigint
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint; v_id bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM proibicao_aluno_equipamento WHERE id=p_proibicao;
    PERFORM contexto_operacao(p_aluno,p_justificativa);
    INSERT INTO solicitacao_reativacao(laboratorio_id,proibicao_id,solicitado_por,justificativa)
    VALUES(v_lab,p_proibicao,p_aluno,p_justificativa) RETURNING id INTO v_id;
    RETURN v_id;
END $$;
CREATE FUNCTION responder_reativacao(p_chefe bigint,p_solicitacao bigint,p_aprovar boolean,p_resposta text) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM solicitacao_reativacao WHERE id=p_solicitacao;
    PERFORM 1 FROM laboratorio WHERE id=v_lab FOR UPDATE;
    PERFORM contexto_operacao(p_chefe,p_resposta);
    IF p_aprovar IS NULL THEN RAISE EXCEPTION 'Informe aprovação ou negação' USING ERRCODE='23514'; END IF;
    UPDATE solicitacao_reativacao SET estado=CASE WHEN p_aprovar THEN 'APROVADA'::estado_solicitacao ELSE 'NEGADA'::estado_solicitacao END,
        respondida_em=clock_timestamp(),respondida_por=p_chefe,resposta=p_resposta WHERE id=p_solicitacao;
END $$;

CREATE FUNCTION tg_validar_protocolo() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    PERFORM exigir_isolamento();
    PERFORM 1 FROM laboratorio WHERE id=NEW.laboratorio_id FOR UPDATE;
    IF TG_OP='INSERT' THEN
        PERFORM exigir_usuario(NEW.autor_id,NEW.laboratorio_id);
        IF NEW.assinado_em IS NOT NULL OR NEW.estado<>'NAO_VALIDADO' THEN
            RAISE EXCEPTION 'Protocolo inicia não validado e sem assinatura' USING ERRCODE='23514';
        END IF;
    ELSE
        IF (NEW.id,NEW.laboratorio_id,NEW.autor_id,NEW.criado_em) IS DISTINCT FROM (OLD.id,OLD.laboratorio_id,OLD.autor_id,OLD.criado_em) THEN
            RAISE EXCEPTION 'Identidade e autoria do protocolo são imutáveis' USING ERRCODE='23514';
        END IF;
        IF OLD.assinado_em IS NOT NULL AND (NEW.pdf_original,NEW.nome_arquivo,NEW.titulo,NEW.assinado_em,NEW.assinado_por)
            IS DISTINCT FROM (OLD.pdf_original,OLD.nome_arquivo,OLD.titulo,OLD.assinado_em,OLD.assinado_por) THEN
            RAISE EXCEPTION 'Protocolo assinado não pode mudar conteúdo ou assinatura' USING ERRCODE='23514';
        END IF;
        IF OLD.estado='VALIDADO' AND (NEW.estado,NEW.validado_em,NEW.validado_por) IS DISTINCT FROM (OLD.estado,OLD.validado_em,OLD.validado_por) THEN
            RAISE EXCEPTION 'Validação de protocolo é imutável' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER validar_protocolo BEFORE INSERT OR UPDATE ON protocolo FOR EACH ROW EXECUTE FUNCTION tg_validar_protocolo();
CREATE FUNCTION tg_vincular_protocolo() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM protocolo WHERE id=NEW.protocolo_id AND estado='VALIDADO') THEN
        RAISE EXCEPTION 'Somente protocolo validado pode ser vinculado' USING ERRCODE='23514';
    END IF;
    PERFORM exigir_chefe(NEW.vinculado_por,NEW.laboratorio_id);
    RETURN NEW;
END $$;
CREATE TRIGGER vincular_protocolo BEFORE INSERT OR UPDATE ON protocolo_equipamento FOR EACH ROW EXECUTE FUNCTION tg_vincular_protocolo();
CREATE FUNCTION assinar_protocolo(p_autor bigint,p_protocolo bigint) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
BEGIN
    PERFORM contexto_operacao(p_autor,'Assinatura do autor');
    UPDATE protocolo SET assinado_em=clock_timestamp(),assinado_por=p_autor WHERE id=p_protocolo AND autor_id=p_autor AND assinado_em IS NULL;
    IF NOT FOUND THEN RAISE EXCEPTION 'Somente o autor pode assinar protocolo ainda não assinado' USING ERRCODE='42501'; END IF;
END $$;
CREATE FUNCTION validar_protocolo(p_chefe bigint,p_protocolo bigint) RETURNS void
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM protocolo WHERE id=p_protocolo;
    PERFORM exigir_chefe(p_chefe,v_lab);
    PERFORM contexto_operacao(p_chefe,'Validação pelo Chefe');
    UPDATE protocolo SET estado='VALIDADO',validado_em=clock_timestamp(),validado_por=p_chefe WHERE id=p_protocolo AND estado='NAO_VALIDADO';
    IF NOT FOUND THEN RAISE EXCEPTION 'Protocolo já validado' USING ERRCODE='23514'; END IF;
END $$;

CREATE FUNCTION tg_movimentar_estoque() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_ator bigint; v_motivo text; v_anterior numeric;
BEGIN
    v_anterior:=CASE WHEN TG_OP='INSERT' THEN 0 ELSE OLD.quantidade END;
    IF NEW.quantidade<>v_anterior THEN
        v_ator:=nullif(current_setting('app.usuario_id',true),'')::bigint;
        v_motivo:=nullif(current_setting('app.motivo',true),'');
        PERFORM exigir_chefe(v_ator,NEW.laboratorio_id);
        IF v_motivo IS NULL THEN RAISE EXCEPTION 'Movimentação de estoque exige motivo' USING ERRCODE='23514'; END IF;
        INSERT INTO movimentacao_estoque(laboratorio_id,item_id,registrado_por,variacao,quantidade_anterior,quantidade_posterior,motivo)
        VALUES(NEW.laboratorio_id,NEW.id,v_ator,NEW.quantidade-v_anterior,v_anterior,NEW.quantidade,v_motivo);
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER movimentar_estoque AFTER INSERT OR UPDATE OF quantidade ON item_estoque FOR EACH ROW EXECUTE FUNCTION tg_movimentar_estoque();
CREATE FUNCTION tg_movimento_origem() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF pg_trigger_depth()<2 THEN
        RAISE EXCEPTION 'Movimentação é gerada pela alteração de saldo do item' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER movimento_origem BEFORE INSERT ON movimentacao_estoque FOR EACH ROW EXECUTE FUNCTION tg_movimento_origem();
CREATE FUNCTION movimentar_estoque(p_chefe bigint,p_item bigint,p_variacao numeric,p_motivo text) RETURNS numeric
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_lab bigint; v_qtd numeric;
BEGIN
    SELECT laboratorio_id INTO STRICT v_lab FROM item_estoque WHERE id=p_item;
    PERFORM exigir_chefe(p_chefe,v_lab);
    PERFORM contexto_operacao(p_chefe,p_motivo);
    IF p_variacao=0 OR p_variacao IS NULL THEN RAISE EXCEPTION 'Variação deve ser diferente de zero' USING ERRCODE='23514'; END IF;
    UPDATE item_estoque SET quantidade=quantidade+p_variacao WHERE id=p_item RETURNING quantidade INTO v_qtd;
    RETURN v_qtd;
END $$;
CREATE FUNCTION avaliar_alertas_estoque(p_laboratorio bigint DEFAULT NULL) RETURNS integer
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v record; v_chave text; v_id bigint; v_total integer:=0;
BEGIN
    -- Executar periodicamente no serviço de tarefas; o banco não agenda SMTP.
    FOR v IN SELECT i.*,l.chefe_usuario_id,l.dias_alerta_validade FROM item_estoque i
             JOIN laboratorio l ON l.id=i.laboratorio_id WHERE i.ativo AND l.ativo
             AND (p_laboratorio IS NULL OR i.laboratorio_id=p_laboratorio) LOOP
        v_chave:='estoque_baixo:'||v.id;
        IF v.quantidade<=v.limite_estoque_baixo THEN
            v_id:=notificar(v.laboratorio_id,v.chefe_usuario_id,'ESTOQUE_BAIXO','Estoque baixo: '||v.nome,
                            jsonb_build_object('item_id',v.id,'quantidade',v.quantidade),v_chave);
            IF v_id IS NOT NULL THEN v_total:=v_total+1; END IF;
        ELSE UPDATE notificacao SET chave_deduplicacao=NULL WHERE destinatario_id=v.chefe_usuario_id AND chave_deduplicacao=v_chave;
        END IF;
        v_chave:='validade:'||v.id;
        IF v.validade IS NOT NULL AND v.validade<=current_date+v.dias_alerta_validade THEN
            v_id:=notificar(v.laboratorio_id,v.chefe_usuario_id,'VALIDADE','Validade próxima ou vencida: '||v.nome,
                            jsonb_build_object('item_id',v.id,'validade',v.validade),v_chave);
            IF v_id IS NOT NULL THEN v_total:=v_total+1; END IF;
        ELSE UPDATE notificacao SET chave_deduplicacao=NULL WHERE destinatario_id=v.chefe_usuario_id AND chave_deduplicacao=v_chave;
        END IF;
    END LOOP;
    RETURN v_total;
END $$;
CREATE FUNCTION tg_notificar_ocorrencia() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_chefe bigint;
BEGIN
    SELECT chefe_usuario_id INTO v_chefe FROM laboratorio WHERE id=NEW.laboratorio_id;
    PERFORM notificar(NEW.laboratorio_id,v_chefe,'OCORRENCIA',NEW.descricao,jsonb_build_object('ocorrencia_id',NEW.id));
    RETURN NEW;
END $$;
CREATE TRIGGER notificar_ocorrencia AFTER INSERT ON ocorrencia FOR EACH ROW EXECUTE FUNCTION tg_notificar_ocorrencia();

-- Auditoria automática, sem credenciais ou conteúdo binário nos snapshots.
CREATE FUNCTION tg_auditar() RETURNS trigger
LANGUAGE plpgsql SET search_path = gestao_lab, public AS $$
DECLARE v_antes jsonb; v_depois jsonb; v_row jsonb; v_lab bigint; v_ator bigint; v_id text;
BEGIN
    v_antes:=CASE WHEN TG_OP<>'INSERT' THEN to_jsonb(OLD)-ARRAY['senha_hash','pdf_original','token_hash'] END;
    v_depois:=CASE WHEN TG_OP<>'DELETE' THEN to_jsonb(NEW)-ARRAY['senha_hash','pdf_original','token_hash'] END;
    v_row:=coalesce(v_depois,v_antes);
    v_lab:=CASE WHEN TG_TABLE_NAME='laboratorio' THEN (v_row->>'id')::bigint ELSE (v_row->>'laboratorio_id')::bigint END;
    v_ator:=nullif(current_setting('app.usuario_id',true),'')::bigint;
    -- Migração/bootstrap sem ator e atuação do sistema são explicitamente NULL.
    IF NOT EXISTS(SELECT 1 FROM usuario WHERE id=v_ator AND laboratorio_id=v_lab) THEN v_ator:=NULL; END IF;
    v_id:=coalesce(v_row->>'id',v_row->>'recurso_id',v_row->>'usuario_id',v_row->>'protocolo_id');
    IF TG_TABLE_NAME='reserva_recurso' THEN v_id:=(v_row->>'reserva_id')||':'||(v_row->>'recurso_id'); END IF;
    IF TG_TABLE_NAME='protocolo_equipamento' THEN v_id:=(v_row->>'protocolo_id')||':'||(v_row->>'equipamento_id'); END IF;
    INSERT INTO historico_uso(laboratorio_id,ator_id,tabela,registro_id,acao,motivo,antes,depois)
    VALUES(v_lab,v_ator,TG_TABLE_NAME,v_id,TG_OP,nullif(current_setting('app.motivo',true),''),v_antes,v_depois);
    RETURN coalesce(NEW,OLD);
END $$;
CREATE FUNCTION tg_impedir_exclusao() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Exclusão física de % bloqueada para preservar histórico; use desativação ou encerramento',TG_TABLE_NAME USING ERRCODE='23514';
END $$;
CREATE FUNCTION tg_historico_imutavel() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Histórico é imutável' USING ERRCODE='23514';
END $$;
DO $$
DECLARE v_tabela text;
BEGIN
    FOREACH v_tabela IN ARRAY ARRAY['laboratorio','usuario','aluno','professor','chefe_laboratorio','recurso','sala','bancada','equipamento',
        'reserva','reserva_recurso','chave','emprestimo_chave','ocorrencia_chave','item_estoque','movimentacao_estoque',
        'protocolo','protocolo_equipamento','proibicao_aluno_equipamento','solicitacao_reativacao','ocorrencia'] LOOP
        EXECUTE format('CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION tg_auditar()',v_tabela);
        EXECUTE format('CREATE TRIGGER impedir_exclusao BEFORE DELETE ON %I FOR EACH ROW EXECUTE FUNCTION tg_impedir_exclusao()',v_tabela);
        EXECUTE format('CREATE TRIGGER impedir_truncate BEFORE TRUNCATE ON %I FOR EACH STATEMENT EXECUTE FUNCTION tg_impedir_exclusao()',v_tabela);
    END LOOP;
END $$;
CREATE TRIGGER historico_imutavel BEFORE UPDATE OR DELETE ON historico_uso FOR EACH ROW EXECUTE FUNCTION tg_historico_imutavel();
CREATE TRIGGER historico_sem_truncate BEFORE TRUNCATE ON historico_uso FOR EACH STATEMENT EXECUTE FUNCTION tg_historico_imutavel();
CREATE TRIGGER movimento_imutavel BEFORE UPDATE ON movimentacao_estoque FOR EACH ROW EXECUTE FUNCTION tg_historico_imutavel();
CREATE TRIGGER ocorrencia_chave_imutavel BEFORE UPDATE ON ocorrencia_chave FOR EACH ROW EXECUTE FUNCTION tg_historico_imutavel();

COMMIT;
